/*
 * generated by Xtext
 */
package org.xtext.example.p4dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class P4DslUiModule extends org.xtext.example.p4dsl.ui.AbstractP4DslUiModule {
	public P4DslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
