/*
* generated by Xtext
*/
package org.xtext.example.p4dsl.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider; 
import org.xtext.example.p4dsl.p4Dsl.Add;
import org.xtext.example.p4dsl.p4Dsl.Edit;
 
import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class P4DslLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public P4DslLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

/*
	//Labels and icons can be computed like this:
	
	String text(Add a) {
	  return "my add";
	}
	 
    String image(Edit edit) {
      return "edit.png";
    }
*/
	
}
