/*
* generated by Xtext
*/
package org.xtext.example.p4dsl.ui.contentassist;

import org.xtext.example.p4dsl.ui.contentassist.AbstractP4DslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class P4DslProposalProvider extends AbstractP4DslProposalProvider {

}
