/*
* generated by Xtext
*/
package org.xtext.example.p4dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class P4DslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.example.p4dsl.ui.internal.P4DslActivator.getInstance().getInjector("org.xtext.example.p4dsl.P4Dsl");
	}
	
}
