/*
* generated by Xtext
*/
package org.xtext.example.p4dsl.ui.outline;
 
import org.eclipse.swt.graphics.Image;
import org.eclipse.xtext.ui.IImageHelper;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.xtext.example.p4dsl.p4Dsl.Add;
import org.xtext.example.p4dsl.p4Dsl.Client;
import org.xtext.example.p4dsl.p4Dsl.Delete;
import org.xtext.example.p4dsl.p4Dsl.Edit;
import org.xtext.example.p4dsl.p4Dsl.Model;
import org.xtext.example.p4dsl.p4Dsl.Port;
import org.xtext.example.p4dsl.p4Dsl.User;

import com.google.inject.Inject;
 
/**
* customization of the default outline structure
*
*/
public class P4DslOutlineTreeProvider extends DefaultOutlineTreeProvider {
 
 @Inject
 private IImageHelper imageHelper;
 
 protected Image _image(Model m) {
 	 return imageHelper.getImage("notepad.png");
 }
 
 protected Image _image(Add a) {
 	 return imageHelper.getImage("add.png");
 }
 
 protected Image _image(Edit e) {
 	 return imageHelper.getImage("edit.png");
 }
 
 protected Image _image(Delete d) {
 	 return imageHelper.getImage("delete.png");
 }
 
 protected Image _image(Port p) {
 	 return imageHelper.getImage("database.png");
 }
 
 protected Image _image(User u) {
 	 return imageHelper.getImage("user-man.png");
 }
 
 protected Image _image(Client c) {
 	 return imageHelper.getImage("computer.png");
 }
 
}
