/*
* generated by Xtext
*/
package org.xtext.example.p4dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class P4DslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
