/*
* generated by Xtext
*/
package org.xtext.example.p4dsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.p4dsl.services.P4DslGrammarAccess;

public class P4DslParser extends AbstractContentAssistParser {
	
	@Inject
	private P4DslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.p4dsl.ui.contentassist.antlr.internal.InternalP4DslParser createParser() {
		org.xtext.example.p4dsl.ui.contentassist.antlr.internal.InternalP4DslParser result = new org.xtext.example.p4dsl.ui.contentassist.antlr.internal.InternalP4DslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getFileBasedCommandAccess().getAlternatives(), "rule__FileBasedCommand__Alternatives");
					put(grammarAccess.getCommandAccess().getGroup(), "rule__Command__Group__0");
					put(grammarAccess.getAddAccess().getGroup(), "rule__Add__Group__0");
					put(grammarAccess.getEditAccess().getGroup(), "rule__Edit__Group__0");
					put(grammarAccess.getDeleteAccess().getGroup(), "rule__Delete__Group__0");
					put(grammarAccess.getModelAccess().getCommandAssignment(), "rule__Model__CommandAssignment");
					put(grammarAccess.getAddAccess().getNameAssignment_1(), "rule__Add__NameAssignment_1");
					put(grammarAccess.getEditAccess().getNameAssignment_1(), "rule__Edit__NameAssignment_1");
					put(grammarAccess.getDeleteAccess().getNameAssignment_1(), "rule__Delete__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.p4dsl.ui.contentassist.antlr.internal.InternalP4DslParser typedParser = (org.xtext.example.p4dsl.ui.contentassist.antlr.internal.InternalP4DslParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public P4DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(P4DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
