/*
 * generated by Xtext
 */
package org.xtext.example.p4dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class P4DslRuntimeModule extends org.xtext.example.p4dsl.AbstractP4DslRuntimeModule {

}
