/*
 * generated by Xtext
 */
package org.xtext.example.p4dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.p4dsl.ui.internal.P4DslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class P4DslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return P4DslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return P4DslActivator.getInstance().getInjector(P4DslActivator.ORG_XTEXT_EXAMPLE_P4DSL_P4DSL);
	}
	
}
